### 피마 인디언 당뇨병 예측

In [1]:
import numpy as np
import pandas as pd

- 1. 데이터 전처리

In [2]:
df = pd.read_csv('pima-indians-diabetes.csv' ,skiprows=9, header=None) 
df  # header=None인 이유는 data header로 읽지말라고

0    1   2   3    4     5      6   7  8
0     6  148  72  35    0  33.6  0.627  50  1
1     1   85  66  29    0  26.6  0.351  31  0
2     8  183  64   0    0  23.3  0.672  32  1
3     1   89  66  23   94  28.1  0.167  21  0
4     0  137  40  35  168  43.1  2.288  33  1
..   ..  ...  ..  ..  ...   ...    ...  .. ..
763  10  101  76  48  180  32.9  0.171  63  0
764   2  122  70  27    0  36.8  0.340  27  0
765   5  121  72  23  112  26.2  0.245  30  0
766   1  126  60   0    0  30.1  0.349  47  1
767   1   93  70  31    0  30.4  0.315  23  0

[768 rows x 9 columns]

In [3]:
# 1. Number of times pregnant
# 2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test
# 3. Diastolic blood pressure (mm Hg)
# 4. Triceps skin fold thickness (mm)
# 5. 2-Hour serum insulin (mu U/ml)
# 6. Body mass index (weight in kg/(height in m)^2)
# 7. Diabetes pedigree function
# 8. Age (years)
# 9. Class variable (0 or 1)
df.columns = ['P', 'G', 'BP', 'S', 'I', 'BMI', 'D', 'Age', 'Target']
df.head()

P    G  BP   S    I   BMI      D  Age  Target
0  6  148  72  35    0  33.6  0.627   50       1
1  1   85  66  29    0  26.6  0.351   31       0
2  8  183  64   0    0  23.3  0.672   32       1
3  1   89  66  23   94  28.1  0.167   21       0
4  0  137  40  35  168  43.1  2.288   33       1

In [ ]:
# 당뇨병 환자가 1
# 당뇨x 0

In [4]:
# 결측치 확인
df.isna().sum().sum()

0

In [5]:
# x data y data
df

P    G  BP   S    I   BMI      D  Age  Target
0     6  148  72  35    0  33.6  0.627   50       1
1     1   85  66  29    0  26.6  0.351   31       0
2     8  183  64   0    0  23.3  0.672   32       1
3     1   89  66  23   94  28.1  0.167   21       0
4     0  137  40  35  168  43.1  2.288   33       1
..   ..  ...  ..  ..  ...   ...    ...  ...     ...
763  10  101  76  48  180  32.9  0.171   63       0
764   2  122  70  27    0  36.8  0.340   27       0
765   5  121  72  23  112  26.2  0.245   30       0
766   1  126  60   0    0  30.1  0.349   47       1
767   1   93  70  31    0  30.4  0.315   23       0

[768 rows x 9 columns]

In [ ]:
# df[열이름][행인덱스]
# df.loc[행인덱스, 열인덱스]
# df.iloc[행숫자, 열숫자]

In [6]:
df.columns

Index(['P', 'G', 'BP', 'S', 'I', 'BMI', 'D', 'Age', 'Target'], dtype='object')

In [ ]:
# X,y 데이터를 ndarray로 추출
X = df[['P', 'G', 'BP', 'S', 'I', 'BMI', 'D', 'Age']].values
y = df.Target.values

In [7]:
df.iloc[:, :-1].values

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
# 일반적인 방법으로 대부분의 CSV 에 적용 가능
# 데이터/ 정답 정해주기
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
# y = df.Target, y= df['Target'] Series 형태의 데이터도 무방, 단 인덱스는 조심
# 시리즈로 주면
# index주면 원래갖고있던 인덱스번호를 갖고있어서 인덱싱할때 틀릴수있어서 불편함이있음
# 웬만하면 넘파이어레이로 변환해서 사용하는게 혼돈을 줄일수있음

In [13]:
# Train / Test 데이터 분리
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(
    X, y,stratify=y,
    test_size=0.2,
    random_state=2023
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((614, 8), (154, 8), (614,), (154,))

In [15]:
# 비율보려고 stratify분포
np.unique(y_train, return_counts=True)

(array([0, 1], dtype=int64), array([400, 214], dtype=int64))

In [16]:
np.unique(y_test, return_counts=True)

(array([0, 1], dtype=int64), array([100,  54], dtype=int64))

In [17]:
# 결정 트리 모델
from sklearn.tree import DecisionTreeClassifier
# 모델 생성 -  객체 생성
dtc = DecisionTreeClassifier(random_state=2023)
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': 2023,
 'splitter': 'best'}

In [19]:
# 학습
dtc.fit(X_train,y_train)

DecisionTreeClassifier(random_state=2023)

In [20]:
# 예측
pred = dtc.predict(X_test)

In [38]:
X_test.shape

(154, 8)

In [21]:
res_df = pd.DataFrame({'y 실제값':y_test, 'y 예측값':pred})
res_df

y 실제값  y 예측값
0        0      0
1        1      1
2        0      0
3        1      1
4        1      0
..     ...    ...
149      0      0
150      0      0
151      0      0
152      0      0
153      0      0

[154 rows x 2 columns]

In [22]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.7402597402597403

In [23]:
params = {
    'max_depth': [2, 5, 8],
    'min_samples_split': [2, 3, 4]
}

In [24]:
from sklearn.model_selection import GridSearchCV

grid_dt = GridSearchCV(
    dtc,        # estimator, Decision Tree Classifier
    param_grid=params,  # parameter를 조합한것 / 파라메터의 조함 / 
    scoring='accuracy', # 평가 방법- 정확도
    cv=5    # 교차검증 세트 수 
)

In [25]:
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=2023),
             param_grid={'max_depth': [2, 5, 8],
                         'min_samples_split': [2, 3, 4]},
             scoring='accuracy')

In [26]:
# 베스트 파라메터 조합
grid_dt.best_params_

{'max_depth': 5, 'min_samples_split': 2}

In [27]:
params = {
    'max_depth': [4, 5, 6],
    'min_samples_split': [2, 3, 4]
}

In [28]:
grid_dt = GridSearchCV(
    dtc, params, scoring='accuracy', cv=5
)
grid_dt.fit(X_train, y_train)

In [30]:
# 베스트 파라메터 조합
grid_dt.fit(X_train, y_train)
grid_dt.best_params_

{'max_depth': 6, 'min_samples_split': 3}

In [31]:
grid_dt.best_score_

0.7491803278688525

- 예측 및 평가 - 학습과정에서 최적의 파라메터로 훈련한 모델로 수행

In [32]:
best_dt = grid_dt.best_estimator_
pred = grid_dt.predict(X_test)
res_dt = pd.DataFrame({'y_실제값':y_test, 'y_예측값':pred})
res_dt.head()

y_실제값  y_예측값
0      0      0
1      1      1
2      0      0
3      1      1
4      1      1

In [33]:
# 50몇프로 90 몇프로 아주이상한 값이 아니면 그냥 넘어가라
best_dt.score(X_test, y_test)

0.7207792207792207

- 실제 적용

In [34]:
X_test[10], y_test[10]

(array([  0.   , 101.   ,  62.   ,   0.   ,   0.   ,  21.9  ,   0.336,
         25.   ]),
 0)

In [35]:
test_data, test_target = X_test[10], y_test[10]

In [39]:
test_data.shape

(8,)

In [41]:
# 예측은 best_dt로
# 위에 predict했을때 X_test를 줬는데 X_test의 shape은 2차원
# test_data.shape (8,)을 2차원으로 바꿔야 (1,8)

# predict() 메소드를 사용하기 위해서는 2차원 모양이 되어야함
result = best_dt.predict(test_data.reshape(1,-1))[0]
result
# 내가 예측한 10번째값이 0이었는데 결과도 0으로 맞춘것임...

0